# Generated by Django 6.0.2 on 2026-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verset_du_jour', models.TextField(help_text='Verset en arabe et en français')),
                ('beuyit_du_jour', models.TextField(help_text='vers de khassida')),
                ('rappel_dujour', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourate', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('traduction_fr', models.TextField()),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='audios/coran')),
            ],
        ),
        migrations.CreateModel(
            name='Khassida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(default='Cheikh Ahmadou Bamba ', max_length=255)),
                ('fichier_pdf', models.FileField(upload_to='pdfs/khassidas')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
            ],
        ),
        migrations.CreateModel(
            name='ParametresPriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(default='Touba', max_length=100)),
                ('activer_adhan', models.BooleanField(default=True)),
                ('fichier_adhan', models.FileField(blank=True, null=True, upload_to='audios/adhan')),
                ('rappel_avant_priere', models.IntegerField(default=15, help_text="Minutes avant l'heure de la prière")),
            ],
        ),
        migrations.CreateModel(
            name='Wird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('transcription', models.TextField(help_text='Transcription')),
                ('traduction', models.TextField(help_text='Traduction')),
                ('nombre_repetitions', models.IntegerField(default=100)),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='audios/wird')),
            ],
        ),
        migrations.CreateModel(
            name='Zikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('texte_arabe', models.TextField()),
                ('texte_francais', models.TextField()),
                ('nombre_repetitions', models.IntegerField(default=100)),
            ],
        ),
    ]
