# Generated by Django 6.0.2 on 2026-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonKhassida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur_voix', models.CharField(help_text='Nom du Kourel ou du rajazz', max_length=100)),
                ('fichier_audio', models.FileField(upload_to='audios/khassidas')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
