# Generated by Django 6.0.2 on 2026-03-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_sonkhassida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coran',
            old_name='sourate',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='wird',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='zikr',
            old_name='nom',
            new_name='titre',
        ),
    ]
