# Generated by Django 6.0.2 on 2026-03-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_rename_sourate_coran_titre_rename_nom_wird_titre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zikr',
            name='nombre_repetitions',
        ),
        migrations.RemoveField(
            model_name='zikr',
            name='texte_arabe',
        ),
        migrations.RemoveField(
            model_name='zikr',
            name='texte_francais',
        ),
        migrations.AddField(
            model_name='zikr',
            name='auteur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zikr',
            name='fichier_audio',
            field=models.FileField(blank=True, null=True, upload_to='zikrs_audio/'),
        ),
        migrations.AddField(
            model_name='zikr',
            name='objectif_par_defaut',
            field=models.PositiveIntegerField(default=33),
        ),
        migrations.AddField(
            model_name='zikr',
            name='texte_a_repeter',
            field=models.TextField(default=100, help_text='La formule à réciter (ex: SubhanAllah)'),
            preserve_default=False,
        ),
    ]
