# Generated by Django 6.0.2 on 2026-03-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_remove_zikr_nombre_repetitions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zikr',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='zikr',
            name='texte_a_repeter',
        ),
        migrations.AddField(
            model_name='zikr',
            name='texte_arabe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zikr',
            name='traduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zikr',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
