# Generated by Django 6.0.2 on 2026-03-13 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_remove_zikr_auteur_remove_zikr_texte_a_repeter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueZikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateTimeField(auto_now_add=True)),
                ('nombre_total', models.PositiveIntegerField()),
                ('zikr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.zikr')),
            ],
        ),
    ]
