# Generated by Django 6.0.2 on 2026-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_historiquezikr'),
    ]

    operations = [
        migrations.AddField(
            model_name='coran',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/coran'),
        ),
        migrations.AlterField(
            model_name='coran',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coran',
            name='traduction_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
