# Generated by Django 6.0.3 on 2026-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_coran_fichier_pdf_alter_coran_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('CORAN', 'Coran'), ('KHASSIDA', 'Khassida'), ('ADHAN', 'Adhan'), ('WAKHTANE', 'Wakhtane'), ('XAM_XAM', 'Xam Xam'), ('ZIKR', 'Zikr'), ('RAJASS', 'Rajass')], default='KHASSIDA', max_length=20)),
                ('fichier_audio', models.FileField(upload_to='audios/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Son',
                'verbose_name_plural': 'Sons',
            },
        ),
    ]
