# Generated by Django 6.0.2 on 2026-03-14 10:31

import bibliotheque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_son'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SonKhassida',
        ),
        migrations.AlterModelOptions(
            name='son',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Son', 'verbose_name_plural': 'Sons'},
        ),
        migrations.AddField(
            model_name='son',
            name='auteur_voix',
            field=models.CharField(blank=True, help_text='Nom du Kourel, du conférencier ou du Rajass', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='fichier_audio',
            field=models.FileField(upload_to=bibliotheque.models.upload_path),
        ),
    ]
