# Generated by Django 6.0.2 on 2026-03-16 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_son'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_lecture', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_lecture'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=50)),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_premium', models.BooleanField(default=False)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('type_soutien', models.CharField(choices=[('DON', 'Don'), ('ABO', 'Abonnement')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('derniere_lecture', models.DateTimeField(auto_now=True)),
                ('termine', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Générale',
            },
        ),
        migrations.DeleteModel(
            name='SonKhassida',
        ),
        migrations.AlterModelOptions(
            name='son',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Son', 'verbose_name_plural': 'Sons'},
        ),
        migrations.AddField(
            model_name='historiquezikr',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='son',
            name='auteur_voix',
            field=models.CharField(blank=True, help_text='Nom du Kourel, du conférencier ou du Rajass', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coran',
            name='fichier_audio',
            field=models.FileField(blank=True, null=True, upload_to='coran_audio/'),
        ),
        migrations.AlterField(
            model_name='coran',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='coran_pdf/'),
        ),
        migrations.AlterField(
            model_name='khassida',
            name='fichier_pdf',
            field=models.FileField(upload_to='khassidas/'),
        ),
        migrations.AlterField(
            model_name='son',
            name='fichier_audio',
            field=models.FileField(upload_to='sons/'),
        ),
    ]
