# Generated by Django 6.0.2 on 2026-03-21 12:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_historique_historiqueconsultation_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='fichier_audio',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='sons/'),
        ),
    ]
