# Generated by Django 6.0.2 on 2026-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_abonnement',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_soutien',
            field=models.CharField(choices=[('DON', 'Don'), ('ABO', 'Abonnement')], max_length=20, null=True),
        ),
    ]
