# Generated by Django 6.0.2 on 2026-03-30 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0012_progressionlecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wird',
            name='auteur',
            field=models.CharField(default='Cheikh Ahmadou Bamba', max_length=255),
        ),
        migrations.AddField(
            model_name='wird',
            name='description_courte',
            field=models.TextField(blank=True, help_text='Résumé pour la liste'),
        ),
        migrations.AddField(
            model_name='wird',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='wirds/'),
        ),
        migrations.AddField(
            model_name='wird',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wird',
            name='traduction',
            field=models.TextField(blank=True, help_text='Traduction'),
        ),
        migrations.AlterField(
            model_name='wird',
            name='transcription',
            field=models.TextField(blank=True, help_text='Transcription'),
        ),
        migrations.CreateModel(
            name='HistoriqueWird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_max', models.PositiveIntegerField(default=1)),
                ('complete', models.BooleanField(default=False)),
                ('temps_total', models.DurationField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.wird')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeWird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titre_arabe', models.CharField(max_length=255)),
                ('titre_francais', models.CharField(max_length=255)),
                ('texte_arabe', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('traduction_francais', models.TextField(blank=True)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('duree_estimee', models.PositiveIntegerField(default=1, help_text='Minutes')),
                ('notes_spirituelles', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('prep', 'Préparation'), ('protec', 'Protection'), ('invoc', 'Invocation'), ('istighfar', 'Istighfar'), ('shahada', 'Shahada'), ('salawat', 'Salawat'), ('tawheed', 'Tawheed'), ('cloture', 'Clôture'), ('quranic', 'Quranique')], default='invoc', max_length=20)),
                ('conseil_spirituel', models.TextField(blank=True)),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='audios/etapes/')),
                ('wird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='bibliotheque.wird')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('wird', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionWird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_courante', models.PositiveIntegerField(default=1)),
                ('repetitions_faites', models.PositiveIntegerField(default=0)),
                ('temps_ecoule', models.DurationField(blank=True, null=True)),
                ('derniere_modif', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.wird')),
            ],
            options={
                'unique_together': {('user', 'wird')},
            },
        ),
    ]
