# Generated by Django 6.0.2 on 2026-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0013_wird_auteur_wird_description_courte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='fichier_audio',
            field=models.FileField(upload_to='sons/'),
        ),
    ]
