# Generated by Django 6.0.2 on 2026-05-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0014_alter_son_fichier_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khassida',
            name='auteur',
            field=models.CharField(default='Cheikh Ahmadou Bamba', max_length=255),
        ),
    ]
