# Generated by Django 6.0.3 on 2026-06-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0016_telechargement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coran',
            name='titre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='khassida',
            name='titre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='son',
            name='categorie',
            field=models.CharField(choices=[('CORAN', 'Coran'), ('KHASSIDA', 'Khassida'), ('ADHAN', 'Adhan'), ('WAKHTANE', 'Wakhtane'), ('XAM_XAM', 'Xam Xam'), ('ZIKR', 'Zikr'), ('RAJASS', 'Rajass')], db_index=True, default='KHASSIDA', max_length=20),
        ),
        migrations.AlterField(
            model_name='son',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wird',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='zikr',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
