# Generated by Django 6.0.2 on 2026-06-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0017_alter_coran_titre_alter_khassida_titre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionZikrCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Grand Zikr du Vendredi', max_length=200)),
                ('objectif_global', models.PositiveIntegerField(default=100000, help_text='Objectif total à atteindre par la communauté')),
                ('compteur_actuel', models.PositiveIntegerField(default=0, help_text='Progression actuelle')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
                ('zikr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_communautaires', to='bibliotheque.zikr')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationZikrCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.PositiveIntegerField(default=0)),
                ('date_derniere_contribution', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_zikr', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='bibliotheque.sessionzikrcommunautaire')),
            ],
            options={
                'ordering': ['-contribution', 'date_derniere_contribution'],
                'unique_together': {('session', 'utilisateur')},
            },
        ),
    ]
