# Generated by Django 6.0.2 on 2026-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0018_sessionzikrcommunautaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Jeton Firebase Cloud Messaging pour les notifications push', max_length=255, null=True),
        ),
    ]
