# Generated by Django 6.0.2 on 2026-06-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0019_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='lien_audio_externe',
            field=models.URLField(blank=True, help_text='Lien Cloudinary ou externe (prioritaire sur le fichier local)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='fichier_audio',
            field=models.FileField(blank=True, null=True, upload_to='sons/'),
        ),
    ]
