# Generated by Django 6.0.2 on 2026-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0020_son_lien_audio_externe_alter_son_fichier_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coran',
            name='est_premium',
            field=models.BooleanField(default=False, help_text='Cocher pour réserver ce contenu aux utilisateurs Premium'),
        ),
        migrations.AddField(
            model_name='khassida',
            name='est_premium',
            field=models.BooleanField(default=False, help_text='Cocher pour réserver ce contenu aux utilisateurs Premium'),
        ),
        migrations.AddField(
            model_name='son',
            name='est_premium',
            field=models.BooleanField(default=False, help_text='Cocher pour réserver ce contenu aux utilisateurs Premium'),
        ),
        migrations.AddField(
            model_name='wird',
            name='est_premium',
            field=models.BooleanField(default=False, help_text='Cocher pour réserver ce contenu aux utilisateurs Premium'),
        ),
        migrations.AddField(
            model_name='zikr',
            name='est_premium',
            field=models.BooleanField(default=False, help_text='Cocher pour réserver ce contenu aux utilisateurs Premium'),
        ),
    ]
