# Generated by Django 6.0.2 on 2026-06-17 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0021_coran_est_premium_khassida_est_premium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notif_nouveau_contenu',
            field=models.BooleanField(default=True, help_text='Être alerté des nouveaux Khassidas ou Audios'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_prieres',
            field=models.BooleanField(default=True, help_text='Recevoir les rappels de prière'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_wird',
            field=models.BooleanField(default=True, help_text='Recevoir les rappels du wird quotidien'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('PRIERE', 'Prière'), ('WIRD', 'Wird'), ('ZIKR', 'Zikr'), ('NOUVEAU', 'Nouveau Contenu'), ('RAPPEL', 'Rappel Spirituel')], default='RAPPEL', max_length=20)),
                ('url_action', models.CharField(blank=True, help_text='URL vers laquelle rediriger au clic', max_length=255, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
