# Generated by Django 6.0.2 on 2026-06-18 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0022_profile_notif_nouveau_contenu_profile_notif_prieres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionzikrcommunautaire',
            name='zikr_personnalise',
            field=models.TextField(blank=True, help_text="Formule personnalisée si aucun zikr prédéfini n'est choisi", null=True),
        ),
        migrations.AlterField(
            model_name='sessionzikrcommunautaire',
            name='zikr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_communautaires', to='bibliotheque.zikr'),
        ),
    ]
