# Generated by Django 6.0.3 on 2026-06-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0023_sessionzikrcommunautaire_zikr_personnalise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fuseau_horaire',
            field=models.CharField(blank=True, help_text='Ex: Africa/Dakar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude pour le calcul des heures de prières', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude pour le calcul des heures de prières', null=True),
        ),
    ]
