# Generated by Django 6.0.3 on 2026-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0024_profile_fuseau_horaire_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionzikrcommunautaire',
            name='code_partage',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sessionzikrcommunautaire',
            name='est_prive',
            field=models.BooleanField(default=False),
        ),
    ]
