# Generated by Django 6.0.3 on 2026-07-14 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0025_sessionzikrcommunautaire_code_partage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKaamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='KAAMIL BI - Lecture du Coran', help_text='Titre de la session', max_length=200)),
                ('est_prive', models.BooleanField(default=False, help_text='Si coché, accessible uniquement par lien')),
                ('code_partage', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_kaamil_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JukkiKaamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numéro du Jukki (1 à 30)')),
                ('est_termine', models.BooleanField(default=False)),
                ('date_prise', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jukkis_pris', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jukkis', to='bibliotheque.sessionkaamil')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('session', 'numero')},
            },
        ),
    ]
