# Generated by Django 6.0.3 on 2026-08-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0026_sessionkaamil_jukkikaamil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(default='fa-solid fa-book', help_text='Classe FontAwesome', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('points_requis', models.IntegerField(default=0, help_text='Points cumulés nécessaires pour débloquer ce niveau')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='DefiMultijoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_partage', models.CharField(blank=True, max_length=10, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_crees', to=settings.AUTH_USER_MODEL)),
                ('niveau_choisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.niveauquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('explication', models.TextField(blank=True, help_text='Affiché après réponse pour éduquer le joueur', null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bibliotheque.categoriequiz')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bibliotheque.niveauquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='bibliotheque.question')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_totaux', models.IntegerField(default=0)),
                ('niveau_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.niveauquiz')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationDefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='bibliotheque.defimultijoueur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('defi', 'utilisateur')},
            },
        ),
    ]
