# Generated by Django 6.0.2 on 2026-09-06 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0027_categoriequiz_niveauquiz_defimultijoueur_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TazawwudBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(max_length=100)),
                ('condition', models.CharField(help_text="Description de la condition d'obtention", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TazawwudLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('texte_source', models.TextField(blank=True, help_text='Texte original du livre', null=True)),
                ('explication', models.TextField(blank=True, help_text='Explication pédagogique', null=True)),
                ('a_retenir', models.TextField(blank=True, help_text='Points clés (Markdown)', null=True)),
                ('vers_debut', models.IntegerField(blank=True, null=True)),
                ('vers_fin', models.IntegerField(blank=True, null=True)),
                ('est_revision_finale', models.BooleanField(default=False, help_text="Vrai si c'est la révision intense de fin de module")),
            ],
            options={
                'ordering': ['module__numero', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='TazawwudModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icone', models.CharField(default='fa-book-open', max_length=100)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TazawwudConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='bibliotheque.tazawwudlecon')),
            ],
        ),
        migrations.AddField(
            model_name='tazawwudlecon',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='bibliotheque.tazawwudmodule'),
        ),
        migrations.CreateModel(
            name='TazawwudProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.IntegerField(default=0)),
                ('serie_jours', models.IntegerField(default=0)),
                ('derniere_activite', models.DateField(auto_now=True)),
                ('concepts_a_revoir', models.ManyToManyField(blank=True, related_name='users_a_revoir', to='bibliotheque.tazawwudconcept')),
                ('concepts_maitrises', models.ManyToManyField(blank=True, related_name='users_maitrises', to='bibliotheque.tazawwudconcept')),
                ('lecon_courante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.tazawwudlecon')),
                ('lecons_terminees', models.ManyToManyField(blank=True, related_name='users_termines', to='bibliotheque.tazawwudlecon')),
                ('module_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.tazawwudmodule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tazawwud_progression', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TazawwudQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('type_question', models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai/Faux')], default='qcm', max_length=20)),
                ('explication_reponse', models.TextField(help_text="S'affiche après la réponse pour expliquer")),
                ('points', models.IntegerField(default=10)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bibliotheque.tazawwudlecon')),
            ],
        ),
        migrations.CreateModel(
            name='TazawwudChoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='bibliotheque.tazawwudquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TazawwudUserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.tazawwudbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tazawwud_badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
